import { parseFeatureManifest } from "../feature-manifest"

export default parseFeatureManifest({
  capabilities: ["clientWorkflows"],
  capabilityResources: [
    {
      capability: "clientWorkflows",
      ownedPaths: [
        "app/composition/generated/client-workflow-ports.ts",
        "app/composition/generated/redux-reducers.ts",
        "app/composition/generated/redux-sagas.ts",
        "app/store",
      ],
      packages: {
        dependencies: ["react-redux", "redux", "redux-saga"],
        devDependencies: [],
        scripts: [],
      },
    },
  ],
  checks: [
    "pnpm exec vitest run app/features/chat app/routes/chat.events.test.ts app/routes/chat.presence.test.ts app/routes/chat.typing.test.ts app/routes/owner.chats.test.ts app/routes/owner.claim.test.ts",
  ],
  conflicts: [],
  defaultEnabled: true,
  dependencies: [],
  description:
    "Private founder conversations with realtime delivery, notifications, drafts, presence, and typing indicators.",
  docs: ["README.md"],
  envKeys: [
    "CHAT_ATTACHMENT_DIRECTORY",
    "OWNER_EMAIL_ALLOWLIST",
    "OWNER_PHONE_NUMBER",
    "TWILIO_ACCOUNT_SID",
    "TWILIO_AUTH_TOKEN",
    "TWILIO_FROM_NUMBER",
  ],
  id: "founderChat",
  migrations: [
    "prisma/migrations/20260717153000_add_owner_chat",
    "prisma/migrations/20260805100800_add_chat_typing_state",
  ],
  name: "Founder chat",
  ownedPaths: [
    "app/features/chat",
    "app/routes/chat.attachments.$attachmentId.tsx",
    "app/routes/chat.events.test.ts",
    "app/routes/chat.events.tsx",
    "app/routes/chat.presence.test.ts",
    "app/routes/chat.presence.tsx",
    "app/routes/chat.tsx",
    "app/routes/chat.typing.test.ts",
    "app/routes/chat.typing.tsx",
    "app/routes/owner.chats.$conversationId.tsx",
    "app/routes/owner.chats.test.ts",
    "app/routes/owner.chats.tsx",
    "app/routes/owner.claim.test.ts",
    "app/routes/owner.claim.tsx",
    "app/routes/settings.test.ts",
    "app/store/store-provider.test.tsx",
    "playwright/e2e/chat.e2e.ts",
  ],
  packages: {
    dependencies: ["twilio"],
    devDependencies: [],
    scripts: [],
  },
  prisma: {
    schemaSlots: [
      "founderChatModels",
      "founderChatUserPresence",
      "founderChatUserRelations",
    ],
  },
  routes: [
    "app/routes/chat.attachments.$attachmentId.tsx",
    "app/routes/chat.events.tsx",
    "app/routes/chat.presence.tsx",
    "app/routes/chat.tsx",
    "app/routes/chat.typing.tsx",
    "app/routes/owner.chats.$conversationId.tsx",
    "app/routes/owner.chats.tsx",
    "app/routes/owner.claim.tsx",
  ],
  sourceSlots: [
    {
      contribution: "founderChatProviderImports",
      slot: "authenticatedProviders",
    },
    {
      contribution: "founderChatProviderLifecycle",
      slot: "authenticatedProviders",
    },
    { contribution: "founderChatProviders", slot: "authenticatedProviders" },
    { contribution: "founderChatEnvDocs", slot: "documentation" },
    {
      contribution: "founderChatEnvFields",
      slot: "serverEnvExtensions",
    },
    {
      contribution: "founderChatOwnerEnvFields",
      slot: "serverEnvExtensions",
    },
    {
      contribution: "founderChatTwilioFields",
      slot: "serverEnvExtensions",
    },
    {
      contribution: "founderChatTwilioValidation",
      slot: "serverEnvExtensions",
    },
    {
      contribution: "founderChatEnvServerImports",
      slot: "serverEnvExtensions",
    },
    {
      contribution: "founderChatEnvServerType",
      slot: "serverEnvExtensions",
    },
    {
      contribution: "founderChatEnvServerDefaults",
      slot: "serverEnvExtensions",
    },
    {
      contribution: "founderChatDoctorIntegrations",
      slot: "serverEnvExtensions",
    },
    { contribution: "founderChatHome", slot: "homeContent" },
    { contribution: "founderChatHomeImports", slot: "homeContent" },
    { contribution: "founderChatNavigation", slot: "primaryNavigation" },
    { contribution: "founderChatReducer", slot: "reduxReducers" },
    { contribution: "founderChatReducerImports", slot: "reduxReducers" },
    { contribution: "founderChatSaga", slot: "reduxSagas" },
    { contribution: "founderChatSagaImports", slot: "reduxSagas" },
    { contribution: "founderChatSagaPorts", slot: "reduxSagas" },
    { contribution: "founderChatClientPortImports", slot: "reduxSagas" },
    { contribution: "founderChatClientPorts", slot: "reduxSagas" },
    { contribution: "founderChatServerPorts", slot: "reduxSagas" },
    { contribution: "founderChatSettings", slot: "settingsLinks" },
    { contribution: "founderChatSettingsData", slot: "settingsLinks" },
    { contribution: "founderChatSettingsImports", slot: "settingsLinks" },
    { contribution: "founderChatSettingsLink", slot: "settingsLinks" },
    { contribution: "founderChatSettingsUiImports", slot: "settingsLinks" },
    { contribution: "founderChatSettingsLoader", slot: "settingsLinks" },
    { contribution: "founderChatE2eHelpers", slot: "testHelpers" },
    { contribution: "founderChatUserFactoryInput", slot: "testHelpers" },
    { contribution: "founderChatUserFactoryOutput", slot: "testHelpers" },
    { contribution: "founderChatAuthTestUser", slot: "testHelpers" },
    { contribution: "founderChatIndexMocks", slot: "testHelpers" },
    {
      contribution: "founderChatEnvServerDefaultsTest",
      slot: "testHelpers",
    },
    { contribution: "founderChatTwilioEnvTest", slot: "testHelpers" },
    { contribution: "founderChatOptionalEnvTest", slot: "testHelpers" },
  ],
})
